"LR": 0.002
"NUM_ENVS": 128
"NUM_STEPS": 128 
"TOTAL_TIMESTEPS": 1e7
"FC_DIM_SIZE": 128 # TODO: why can't I change this to 256?
"GRU_HIDDEN_DIM": 128
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.0
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.25
"ACTIVATION": "relu"
"OBS_WITH_AGENT_ID": False # True
"ENV_NAME": "HeuristicEnemySMAX"
"MAP_NAME": "3M3z"
"SEED": 0
"NUM_SEEDS": 3
"ENV_KWARGS": 
  "see_enemy_actions": True
  "walls_cause_death": True
  "attack_mode": "closest"
"ANNEAL_LR": True

# WandB Params
"ENTITY": "star-lab-gt"
"PROJECT": "JaxMARL"
"WANDB_MODE": "online"
"RUN_NAME": "class-id"
