# experiment params
"NUM_SEEDS": 1
"SEED": 76

# wandb params
"ENTITY": "star-lab-gt"
"PROJECT": "JaxMARL"
"WANDB_MODE": "online"

# where to save the params (if None, will not save)
"SAVE_PATH": "baselines/QLearning/checkpoints"

# NOTE: only works for MPE right now
"VISUALIZE_FINAL_POLICY": False
# number of seeds/envs to visualize
"VIZ_NUM_ENVS": 3
"VIZ_NUM_SEEDS": 2
