NUM_ENVS: 8
PARAMETERS_SHARING: True

# NOTE: NUM_STEPS (max_steps_per_env) defined by env.yaml
TRAJECTORIES_PER_ENV: 32
# BUFFER_SIZE = NUM_ENVS * TRAJECTORIES_PER_ENV
# TODO: I believe this batch size is actually 32 trajectories, not 32 steps
BUFFER_BATCH_SIZE: 32
# TRAIN_ITERS: 1000

# agent network params
PARAMETERS_SHARING: True
AGENT_HIDDEN_DIM: 32 # width of the RNN hidden dim + surrounding MLP layers
AGENT_RECURRENT: True
AGENT_INIT_SCALE: 2.
AGENT_HYPERAWARE: True
AGENT_HYPERNET_HIDDEN_DIM: 16 # width of hypernet
AGENT_HYPERNET_INIT_SCALE: 0.2 # NOTE: MUST TUNE THIS
