# TODO: how to transfer policies to RL? save and reload probably easiest

NUM_ENVS: 8
PARAMETERS_SHARING: True

# NOTE: NUM_STEPS (max_steps_per_env) defined by env.yaml
BUFFER_SIZE: 10000
BUFFER_BATCH_SIZE: 32
# TRAIN_ITERS: 1000
