NUM_ENVS: 8
# NOTE: NUM_STEPS now defined by config.env.env_kwargs.max_steps
BUFFER_SIZE: 5000
BUFFER_BATCH_SIZE: 32
TOTAL_TIMESTEPS: 4e6 # 2050000

# agent network params
PARAMETERS_SHARING: True
AGENT_HIDDEN_DIM: 32 # width of the RNN hidden dim + surrounding MLP layers
AGENT_RECURRENT: True
AGENT_INIT_SCALE: 2.
AGENT_HYPERAWARE: True
AGENT_HYPERNET_HIDDEN_DIM: 16 # width of hypernet
AGENT_HYPERNET_INIT_SCALE: 0.2 # NOTE: MUST TUNE THIS

EPSILON_START: 1.0
EPSILON_FINISH: 0.05
EPSILON_ANNEAL_TIME: 100000
MIXER_EMBEDDING_DIM: 32
MIXER_HYPERNET_HIDDEN_DIM: 64
MIXER_INIT_SCALE: 0.00001
MAX_GRAD_NORM: 25
TARGET_UPDATE_INTERVAL: 200
LR: 0.005
LR_LINEAR_DECAY: True
EPS_ADAM: 0.001
WEIGHT_DECAY_ADAM: 0.00001
TD_LAMBDA_LOSS: True
TD_LAMBDA: 0.6
GAMMA: 0.9
VERBOSE: False
WANDB_ONLINE_REPORT: True
NUM_TEST_EPISODES: 32
TEST_INTERVAL: 50000
