"ENV_NAME": "MPE_sensor_network"
"ENV_KWARGS":
  "capability_aware": True # T/F
  "max_steps": 25

  # capabilities implemented in MPE_sensor_network: [cover_rad]
  "num_capabilities": 2
  "num_agents": 3

  # NOTE: if these lists are longer than num_agents, env will sample num_agents randomly from them each train iter
  # NOTE: hijacking agent_rads = firefighting capability
  "agent_rads": [0.3, 0.1, 0.1]
  "agent_accels": [1, 3, 3]

  # "test_team":
  #   "agent_rads": [0.15, 0.15, 0.15, 0.15]
  #   "agent_accels": [1, 1, 1, 1]

