"ENV_NAME": "MPE_simple_spread_v3"
"ENV_KWARGS":
  "capability_aware": True # T/F

  "num_agents": 3
  "num_landmarks": 3
  # capabilities implemented in MPE_simple_spread_v3: [accel, rad]
  "num_capabilities": 2
  # default accel in MPE is 5 (applies even for discrete actions)
  # default rad for agents is 0.15 (for landmarks is 0.05)
  "agent_rads": [0.20, 0.12, 0.15, 0.12, 0.15]
  "agent_accels": [5, 5, 5, 5, 5]
  # TODO: add test time capabilities

  # [[rad, accel]_1, [r, a]_2, ...]
  # "agent_capabilities": [[0.20, 5], [0.12, 5], [0.15, 5], [0.12, 5], [0.15, 5]]
  # "test_capabilities": [[0.3, 5], [0.08, 5], [0.08, 5]]
