"ENV_NAME": "MPE_simple_fire"
"ENV_KWARGS":
  "capability_aware": True # T/F
  "max_steps": 50 # 25

  # capabilities implemented in MPE_simple_fire: [fire_fight_cap, accel]
  "num_capabilities": 2
  "num_agents": 3

  # NOTE: if these lists are longer than num_agents, env will sample num_agents randomly from them each train iter
  # NOTE: hijacking agent_rads = firefighting capability
  "agent_rads": [0.3, 0.2, 0.1, 0.1, 0.2]
  "agent_accels": [1, 2, 3, 3, 2]

  "test_team":
    "agent_rads": [0.4, 0.08, 0.08]
    "agent_accels": [1, 3, 3]

  # TODO: add rew shaping constants to YAML

