"ENV_NAME": "MPE_simple_spread_v3"
"ENV_KWARGS":
  "num_agents": 3
  "num_landmarks": 3

  "capability_aware": True # T/F
  # default accel in MPE is 5
  # applies even for discrete actions
  "accel": [5, 5, 5]
  # default for agents is 0.15, for landmarks is 0.05
  "rad": [0.08, 0.15, 0.30, 0.05, 0.05, 0.05]
